version: '3.8'


services:
  api:
    build: .
    ports:
      - 80:80
    environment:
      APP_MODULE: shopping_list.main:app
      DB_DSN: ${DB_DSN}
    networks:
      - default
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend


networks:
  backend:
