"""User

Revision ID: 8a3fda4b00a3
Revises: a72ee20a3055
Create Date: 2021-09-21 17:06:14.351716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a3fda4b00a3'
down_revision = 'a72ee20a3055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('list', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('list', sa.Column('name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'list', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list', type_='foreignkey')
    op.drop_column('list', 'name')
    op.drop_column('list', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
