"""Sharing list table

Revision ID: e3b34d35356a
Revises: d9129f1385be
Create Date: 2021-10-22 19:50:56.382780

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = 'e3b34d35356a'
down_revision = 'd9129f1385be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'share',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('share_type', postgresql.ENUM('RO', 'RW', name='sharingoptions'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('list_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['list_id'],
            ['list.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share')
    # ### end Alembic commands ###
